### ISSUE TITLE
Implement ORCA 5 import

### ISSUE THREAD

**Issue by stestoll** [StollLab/EasySpin#219]
ORCA 5 discontinues the binary .prop property file and introduces a new text-based file format. This needs to be implemented in `orca2easyspin`.

**Comment by stestoll** [comment]
The problem with the new property file (called `job_property.txt` for a calculation called `job`), has a series of peculiarities/bugs. For ORCA 5.0.1, I ran into the following
- Under EPRNMR_GTensor, the g tensor is missing. (Eigenvectors and eigenvalues are present).
- Under EPRNMR_QTensor, the tensor stored is the hyperfine tensor, not the quadrupole tensor.
- Under EPRNMR_QTensor, the principal values are not from the Q tensor, but from the EFG tensor.
The main output file appears to be more reliable in this regard.

**Comment by stestoll** [comment]
See [post on ORCA forum](https://orcaforum.kofo.mpg.de/viewtopic.php?f=11&t=8118).

**Comment by iowachem** [comment]
Is this issue fixed in the  easyspin version 5.2.35?

**Comment by stestoll** [comment]
No, only in 6.0.

**Comment by dinarabdullin** [comment]
Dear Stefan,
I still get this issue, even with the newest Orca (5.0.4) and EasySpin (6.0.0-dev53) versions. Here is the error message:
"
eulang: Rotation matrix is not orthogonal within 1e-6.
Error using orca2easyspin_proptxt
EPRNMR_QTensor is not supported.
Error in orca2easyspin
"
Kind regards,
Dinar

**Comment by cetait** [comment]
See issue https://github.com/StollLab/EasySpin/issues/230, using orca2easyspin with the ORCA output file instead of the property text file should work.

**Comment by dinarabdullin** [comment]
Thank you Claudia, I just found it myself too:) It would be useful to update the documentation
